Compiling Species Ranges
========================

#Step 1
Download Barone's data for all 3 transects in Puerto Rico

#Step 2
Created a csv file (Barone.ranges) that includes only species found in the Sonadora transect

#Step 3
Filled in family, genus, and species name for each record based on 6 letter species code given

#Step 4
Determined the upper and lower range limits for each species using Barone's data from all 3 transects

#Step 5
Adjusted the upper and lower range limits if the species is found within the LTER plot
Made lower range 350m and upper range 400m if found within the plot and range did not already exceed these values

#Step 6
Adjusted the ranges based on F. Axelrod's book, "A systematic vademecum to the vascular plants of Puerto Rico"

#Step 7
Adjusted the taxonomy of species to match updated taxonomy in Axelrod's book

#Step 8
Added a new column to Barone.ranges and calculated species range in this column in Excel

```{r eval=F}
range = upper.range - lower.range

```

#Step 9
Adjusted the species in the dataset based on available trait data


